# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/remote/Desktop/infineon/ComLib_C_Interface/examples/S2GLP_basics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/remote/Desktop/infineon/ComLib_C_Interface/examples/S2GLP_basics/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/remote/Desktop/infineon/ComLib_C_Interface/examples/S2GLP_basics/build/CMakeFiles /home/remote/Desktop/infineon/ComLib_C_Interface/examples/S2GLP_basics/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/remote/Desktop/infineon/ComLib_C_Interface/examples/S2GLP_basics/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named s2glp_basics

# Build rule for target.
s2glp_basics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 s2glp_basics
.PHONY : s2glp_basics

# fast build rule for target.
s2glp_basics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/build
.PHONY : s2glp_basics/fast

commlib24_S2GLP_basics.o: commlib24_S2GLP_basics.c.o

.PHONY : commlib24_S2GLP_basics.o

# target to build an object file
commlib24_S2GLP_basics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/commlib24_S2GLP_basics.c.o
.PHONY : commlib24_S2GLP_basics.c.o

commlib24_S2GLP_basics.i: commlib24_S2GLP_basics.c.i

.PHONY : commlib24_S2GLP_basics.i

# target to preprocess a source file
commlib24_S2GLP_basics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/commlib24_S2GLP_basics.c.i
.PHONY : commlib24_S2GLP_basics.c.i

commlib24_S2GLP_basics.s: commlib24_S2GLP_basics.c.s

.PHONY : commlib24_S2GLP_basics.s

# target to generate assembly for a file
commlib24_S2GLP_basics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/commlib24_S2GLP_basics.c.s
.PHONY : commlib24_S2GLP_basics.c.s

home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.o: home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.o

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.o

# target to build an object file
home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.o
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.o

home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.i: home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.i

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.i

# target to preprocess a source file
home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.i
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.i

home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.s: home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.s

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.s

# target to generate assembly for a file
home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.s
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.c.s

home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.o: home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.o

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.o

# target to build an object file
home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.o
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.o

home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.i: home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.i

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.i

# target to preprocess a source file
home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.i
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.i

home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.s: home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.s

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.s

# target to generate assembly for a file
home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.s
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.c.s

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.o: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.o

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.o

# target to build an object file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.o
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.o

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.i: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.i

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.i

# target to preprocess a source file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.i
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.i

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.s: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.s

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.s

# target to generate assembly for a file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.s
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.c.s

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.o: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.o

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.o

# target to build an object file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.o
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.o

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.i: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.i

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.i

# target to preprocess a source file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.i
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.i

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.s: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.s

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.s

# target to generate assembly for a file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.s
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.c.s

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.o: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.o

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.o

# target to build an object file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.o
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.o

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.i: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.i

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.i

# target to preprocess a source file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.i
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.i

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.s: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.s

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.s

# target to generate assembly for a file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.s
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.c.s

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.o: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.o

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.o

# target to build an object file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.o
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.o

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.i: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.i

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.i

# target to preprocess a source file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.i
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.i

home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.s: home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.s

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.s

# target to generate assembly for a file
home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.s
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.c.s

home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.o: home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.o

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.o

# target to build an object file
home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.o
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.o

home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.i: home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.i

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.i

# target to preprocess a source file
home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.i
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.i

home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.s: home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.s

.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.s

# target to generate assembly for a file
home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/s2glp_basics.dir/build.make CMakeFiles/s2glp_basics.dir/home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.s
.PHONY : home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... s2glp_basics"
	@echo "... commlib24_S2GLP_basics.o"
	@echo "... commlib24_S2GLP_basics.i"
	@echo "... commlib24_S2GLP_basics.s"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.o"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.i"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Unix.s"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.o"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.i"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/COMPort_Windows.s"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.o"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.i"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarBaseBoard.s"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.o"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.i"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarDeviceStatus.s"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.o"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.i"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarErrorCodes.s"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.o"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.i"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/EndpointRadarS2GLP.s"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.o"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.i"
	@echo "... home/remote/Desktop/infineon/ComLib_C_Interface/src/Protocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

